-- CreateTable
CREATE TABLE "courier_service"."couriers" (
    "id" TEXT NOT NULL,
    "externalId" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "isWorking" BOOLEAN NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tckn" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "phone" TEXT,
    "name" TEXT NOT NULL,
    "iv" INTEGER NOT NULL,
    "state" TEXT NOT NULL,
    "DeliverPrepaidOrder" BOOLEAN NOT NULL,
    "restaurantId" TEXT,
    "eteration_device_brand" TEXT,
    "isWorkingFlag" BOOLEAN NOT NULL,
    "posDeviceType" TEXT,
    "onlineReasonId" TEXT,
    "carrierType" INTEGER,
    "countyId" TEXT,
    "licensePlate" TEXT,
    "otherGsm" TEXT,
    "posDeviceId" TEXT,
    "hubId" TEXT,
    "address" TEXT,
    "reasonId" TEXT,
    "eteration_device_token" TEXT,
    "carrierBillingType" INTEGER,
    "imei" TEXT,
    "iban" TEXT,
    "mail" TEXT,
    "taxAreaCode" TEXT,
    "vkn" TEXT,
    "isTest" BOOLEAN NOT NULL,
    "eteration_imei_updated" BOOLEAN NOT NULL,

    CONSTRAINT "couriers_pkey" PRIMARY KEY ("id")
);
